/*
* generated by Xtext
*/
package org.edna.datamodel.ui.contentassist;

import org.edna.datamodel.ui.contentassist.AbstractDatamodelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DatamodelProposalProvider extends AbstractDatamodelProposalProvider {

}
