/*
* generated by Xtext
*/
package org.edna.datamodel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.edna.datamodel.services.DatamodelGrammarAccess;

public class DatamodelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DatamodelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.edna.datamodel.parser.antlr.internal.InternalDatamodelParser createParser(XtextTokenStream stream) {
		return new org.edna.datamodel.parser.antlr.internal.InternalDatamodelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DatamodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DatamodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
