/*
 * generated by Xtext
 */
package org.edna.datamodel.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 *
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it
 *
 */
public class DatamodelScopeProvider extends AbstractDeclarativeScopeProvider {
	IScope scope_Package_types (org.edna.datamodel.datamodel.Package p, EReference ref) {
		return Scopes.scopeFor(p.getTypes());
	}
}
