/*
 * generated by Xtext
 */
package org.edna.datamodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.IContainer;
import org.eclipse.xtext.resource.containers.StateBasedContainerManager;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DatamodelUiModule extends
		org.edna.datamodel.ui.AbstractDatamodelUiModule {
	public DatamodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

//	public Class<? extends IContainer.Manager> bindIContainer$Manager() {
//		return StateBasedContainerManager.class;
//	}

	@Override
	public com.google.inject.Provider<org.eclipse.xtext.resource.containers.IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

}
