/*
 * generated by Xtext
 */
package org.edna.datamodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.edna.datamodel.ui.customizing.DatamodelDocumentationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DatamodelUiModule extends
		org.edna.datamodel.ui.AbstractDatamodelUiModule {
	public DatamodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public com.google.inject.Provider<org.eclipse.xtext.resource.containers.IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider () {
		return DatamodelDocumentationProvider.class;
	}
}
