/*
* generated by Xtext
*/
package org.edna.datamodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DatamodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
