/*
* generated by Xtext
*/
package org.edna.datamodel.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * customization of the default outline structure
 * 
 */
public class DatamodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	@Override
	protected void _createChildren(DocumentRootNode parentNode,
			EObject modelElement) {
		for (EObject content : modelElement.eContents()) {
			createNode(parentNode, content);
		}
	}
}
