/*
* generated by Xtext
*/
package org.edna.datamodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DatamodelTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
