/*
 * generated by Xtext
 */
package org.edna.datamodel;

import org.edna.datamodel.scoping.QualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DatamodelRuntimeModule extends org.edna.datamodel.AbstractDatamodelRuntimeModule {

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return QualifiedNameProvider.class;
	}
}
